spring:
  datasource:
    url: jdbc:mariadb://192.0.4.201:3306/idus
    driver-class-name: org.mariadb.jdbc.Driver
    username: idus
    password: qwer1234
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true




logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
